/* Topic-specific interaction layer. Existing scoring and tracking stay in experience.js. */
(()=>{'use strict';const c=COURSE,e=s=>String(s).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]));
const cfg={
'adkar':{title:'Listen before<br>you prescribe.',sub:'A coaching conversation.<br>A better next move.',mission:'Jordan knows the steps. The results still don’t match.',brief:'Ask for evidence. Find the barrier. Choose support that helps Jordan perform.',number:'01',unit:'PERSON, NOT A LABEL',watch:'Hear the change challenge.',tag:'COACHING STUDIO'},
'adult-learning':{title:'Build the moment<br>learning happens.',sub:'Bring experience.<br>Make room for practice.',mission:'You have 12 minutes. What will learners actually do?',brief:'Turn a lecture into a short activity that produces a decision, feedback and a next step.',number:'12',unit:'MINUTES TO MAKE USEFUL',watch:'Start with the learner’s situation.',tag:'LEARNING WORKSHOP'},
'ebitda':{title:'Build the bridge.<br>Question the number.',sub:'See what adds up.<br>Know what it cannot tell you.',mission:'The number is $190,000. Is that money available to spend?',brief:'Build the earnings bridge, then choose the evidence a spending decision still needs.',number:'190',unit:'$000 / EARNINGS, NOT CASH',watch:'See the measure in context.',tag:'NUMBER STUDIO'},
'jira-cloud':{title:'Give the next person<br>work they can use.',sub:'Define the outcome.<br>Show the evidence.',mission:'“Update training.” Is that enough to hand off?',brief:'Clarify a job-aid request, add acceptance criteria, and move it only as far as the evidence supports.',number:'03',unit:'CHECKS BEFORE HANDOFF',watch:'Watch a work-item decision.',tag:'DELIVERY LAB'},
'confluence-cloud':{title:'Make knowledge<br>easy to act on.',sub:'A useful page.<br>The right reader. Clear ownership.',mission:'Your teammate needs a handoff guide—not another note.',brief:'Build a usable page, check its audience and ownership, then decide whether it is ready to share.',number:'01',unit:'CANONICAL PLACE TO START',watch:'See how shared knowledge works.',tag:'KNOWLEDGE ATELIER'}
}[c.id];if(!cfg)return;
const base=window.Experience;let parts=new Set(),ready=false,confirmed=false;
function film(){return `<section class="watch-stage"><div class="watch-title"><div><p class="eyebrow">WATCH / LISTEN / NOTICE</p><h2>${cfg.watch}</h2></div><span class="film-tag">NARRATED SCENARIO</span></div><video controls preload="metadata" playsinline poster="${c.mediaBase}.jpg" aria-label="Narrated companion scenario"><source src="${c.mediaBase}.mp4" type="video/mp4"><track kind="captions" src="companion.vtt" srclang="en" label="English" default></video><p class="meta">Press play for narration · English captions · Separate fictional companion case</p><details><summary>Read the narration and scenario response</summary><div class="transcript">${e(c.transcript).replaceAll('\n','<br>')}</div><p>${e(c.creative.answer)}</p></details></section>`;}
function debrief(){return `<details class="worked-debrief"><summary>Open the worked explanation</summary><p>${e(c.example.body)}</p><ol>${c.example.steps.map(x=>'<li>'+e(x)+'</li>').join('')}</ol></details>`;}
function jira(){return `<section class="lab"><p class="eyebrow">YOUR TEAM BOARD / FICTIONAL WORKFLOW</p><h2>Build a handoff worth reviewing.</h2><p>Add the missing information. Then choose a status that reflects the evidence.</p><div class="workbench"><article class="work-card"><div class="ticket-top"><span>ENABLE-41</span><b id="item-status">In progress</b></div><h3 id="item-title">Update training</h3><div id="item-criteria" class="empty-slot">Acceptance criteria missing</div><div id="item-evidence" class="empty-slot">Review evidence missing</div></article><div class="tool-drawer"><p class="eyebrow">BUILD THE WORK ITEM</p><button data-studio="scope">＋ Define the deliverable</button><button data-studio="criteria">＋ Add observable criteria</button><button data-studio="draft">＋ Attach the draft evidence</button><button data-studio="confirm">＋ Record reviewer confirmation</button></div></div><div class="actions"><button data-studio="review" class="primary">Move to Review →</button><button data-studio="done">Mark Done ✓</button></div><div id="studio-feedback" class="lab-feedback" role="status">A status should describe the work—not your intention.</div></section>`;}
function confluence(){return `<section class="lab"><p class="eyebrow">PAGE STUDIO / FICTIONAL TEAM SPACE</p><h2>Turn notes into a useful job aid.</h2><p>Build the page and verify the intended reader before sharing.</p><div class="workbench page-workbench"><article class="knowledge-page"><div class="page-breadcrumb">TRAINER ENABLEMENT / DRAFT</div><h3 id="page-task">Notes</h3><div id="page-steps">Send it over. Check with the trainer. Which checklist?</div><div id="page-owner" class="owner-strip">Owner and review date missing</div><div id="page-audience" class="audience-strip">Audience access not checked</div></article><div class="tool-drawer"><p class="eyebrow">EDIT THE PAGE</p><button data-studio="task">＋ Name the reader’s task</button><button data-studio="structure">＋ Structure the handoff</button><button data-studio="owner">＋ Assign owner & review date</button><button data-studio="access">＋ Test reader access</button></div></div><button data-studio="publish" class="primary">Share with the trainer group →</button><div id="studio-feedback" class="lab-feedback" role="status">A link alone does not grant access.</div></section>`;}
function updateFeedback(text){const f=document.querySelector('#studio-feedback');if(f)f.textContent=text;}
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-studio]');if(!b)return;const k=b.dataset.studio;
if(c.id==='jira-cloud')switch(k){case'scope':parts.add(k);document.querySelector('#item-title').textContent='Publish the revised escalation job aid for new trainers';updateFeedback('The outcome now names a deliverable and an audience.');break;case'criteria':parts.add(k);document.querySelector('#item-criteria').innerHTML='<h4>Acceptance criteria</h4><ul><li>Three steps match the approved procedure.</li><li>Headings make the accessible guide easy to navigate.</li><li>Reviewer confirms the final version.</li></ul>';updateFeedback('These criteria can be checked. A vague “looks good” cannot.');break;case'draft':parts.add(k);document.querySelector('#item-evidence').innerHTML='<b>Draft v2 attached</b><p>Author has checked the procedure and headings. Reviewer confirmation is pending.</p>';updateFeedback('Draft evidence is available. Reviewer confirmation is still outstanding.');break;case'confirm':if(!ready){updateFeedback('Send a clear, evidence-backed item to Review first. Confirmation is recorded after the review in this simulation.');return;}confirmed=true;document.querySelector('#item-evidence').innerHTML='<b>Reviewer confirmation recorded</b><p>All three acceptance criteria verified in this fictional review.</p>';updateFeedback('Now the evidence supports Done.');break;case'review':if(!['scope','criteria','draft'].every(x=>parts.has(x))){updateFeedback('The next person cannot review it yet. Add the deliverable, acceptance criteria and draft evidence.');return;}ready=true;document.querySelector('#item-status').textContent='Review';updateFeedback('In Review. The reviewer has a clear deliverable, criteria and evidence. This is not Done yet.');break;case'done':if(!confirmed){updateFeedback('Consequence: Done would claim a review that has not happened. Record the outstanding review and keep the status honest.');return;}document.querySelector('#item-status').textContent='Done';updateFeedback('Done is supported: the reviewer has confirmed the agreed criteria. The status now matches the evidence.');break;}
if(c.id==='confluence-cloud')switch(k){case'task':parts.add(k);document.querySelector('#page-task').textContent='Complete the new-trainer handoff';updateFeedback('A task title tells the reader when to use this page.');break;case'structure':parts.add(k);document.querySelector('#page-steps').innerHTML='<h4>Before you start</h4><p>Have the approved trainer checklist and receiving trainer’s details.</p><h4>Complete the handoff</h4><ol><li>Check the package against the approved checklist.</li><li>Share the approved materials with the receiving trainer.</li><li>Confirm receipt and record unresolved questions.</li></ol><h4>Expected result</h4><p>The receiving trainer has the materials and a named contact for open questions.</p>';updateFeedback('The page now separates prerequisites, actions and the expected result. These are fictional sample steps.');break;case'owner':parts.add(k);document.querySelector('#page-owner').textContent='Owner: Trainer Enablement Lead · Review: 9 January 2027 or on process change';updateFeedback('Ownership makes maintenance someone’s responsibility.');break;case'access':parts.add(k);document.querySelector('#page-audience').textContent='Trainer-group access and parent restrictions checked · Representative reader opened and used the page';updateFeedback('In this simulation, the intended reader can open and use it. Real access must be tested in your tenant.');break;case'publish':if(!['task','structure','owner','access'].every(x=>parts.has(x))){updateFeedback('Sharing now would leave a gap. Check the task, usable steps, ownership and effective audience access before releasing.');return;}document.querySelector('.page-breadcrumb').textContent='TRAINER ENABLEMENT / READY TO SHARE';updateFeedback('Ready to share in this simulation. The page has a clear purpose, usable guidance, maintenance owner and verified audience. No real page was published.');break;}
b.setAttribute('aria-pressed','true');});
window.Experience={reset(){base.reset();parts.clear();ready=false;confirmed=false;},mount(step){base.mount(step);const container=document.querySelector('.fade');
if(step===0){document.querySelector('.hero').outerHTML=`<section class="cinema-hero"><img src="hero-editorial.jpg" alt="${e(c.heroAlt||'Editorial illustration of '+c.title)}"><div class="hero-copy"><p class="eyebrow">${cfg.tag}</p><h1>${cfg.title}</h1><p>${cfg.sub}</p><div class="actions"><button class="primary" data-next>Begin lesson</button><button data-go="2">▶ Watch the scenario</button></div></div></section>`;}
if(step===1){const heading=container.querySelector('h1');heading.textContent='Start with a decision.';container.querySelectorAll('.role-note,.grid').forEach(x=>x.remove());heading.insertAdjacentHTML('afterend',`<div class="mission-scene"><div class="mission-number">${cfg.number}<span>${cfg.unit}</span></div><div><p class="eyebrow">YOUR ASSIGNMENT</p><h2>${cfg.mission}</h2><p>${cfg.brief}</p><button data-go="3" class="primary">Try the activity →</button><p class="meta">Continue for a narrated companion scenario first.</p></div></div><details><summary>Scenario context and delivery role</summary><p>${e(c.creative.role)}</p></details>`);}
if(step===2){container.querySelector('.companion')?.remove();container.querySelector('h1').textContent='Watch. Notice. Apply.';container.querySelector('.intro')?.remove();container.querySelector('h1').insertAdjacentHTML('afterend',film()+'<h2 class="concept-heading">The decision rules</h2>');}
if(step===3){const old=container.querySelector('.lab');container.querySelectorAll('.card').forEach(x=>x.remove());container.querySelector('h1').textContent= c.id==='adkar'?'Coach the next move.':c.id==='adult-learning'?'Design for application.':c.id==='ebitda'?'Build it. Then interpret it.':c.id==='jira-cloud'?'Make the work ready.':'Build a page people can use.';
if(c.id==='jira-cloud')old.outerHTML=jira();else if(c.id==='confluence-cloud')old.outerHTML=confluence();
const active=container.querySelector('.lab');container.querySelector('h1').insertAdjacentElement('afterend',active);active.insertAdjacentHTML('afterend',debrief());
if(c.id==='adkar')active.insertAdjacentHTML('afterbegin','<div class="coach-banner"><span class="coach-monogram">J</span><div><b>Jordan</b><p>“I understand the steps. My ratings still don’t match.”</p></div></div>');
if(c.id==='adult-learning')active.querySelector('.activity-sequence').insertAdjacentHTML('beforebegin','<div class="workshop-meter"><span>CONNECT</span><span>PRACTICE</span><span>FEEDBACK</span></div>');
if(c.id==='ebitda')active.querySelector('.bridge-control').insertAdjacentHTML('afterend','<div class="earnings-meter" aria-label="EBITDA relative to the 190 thousand target"><div id="earnings-fill" style="width:63.16%"></div></div><p class="meta">Build toward $190,000 · Each add-back appears once · This bar represents earnings, not cash</p>');
}}};
document.addEventListener('change',ev=>{if(c.id==='ebitda'&&ev.target.matches('[data-addback]')){let n=120;document.querySelectorAll('[data-addback]:checked').forEach(x=>n+=Number(x.dataset.addback));document.querySelector('#earnings-fill').style.width=(n/190*100)+'%';}});
})();
